FROM hivemq/hivemq-ce
RUN rm -rf /opt/hivemq-ce-2023.4/extensions/hivemq-allow-all-extension
# VOLUME /home/ubuntu/mqtt/hivemq-file-rbac-extension:/opt/hivemq-ce-2023.4/extensions/hivemq-file-rbac-extension


# VOLUME /home/ubuntu/mqtt/hivemq-file-rbac-extension